apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: log-service
data:
  PORT: "3000"
  DATABASE_URL: "mongodb://<db_username>:<db_password>@mongo:27017"
  DATABASE_USERNAME: "admin"
  DATABASE_PASSWORD: "password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
  namespace: log-service
spec:
  selector:
    matchLabels:
      app: log-service
  replicas: 2
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
      - name: log-service
        image: log-service:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: log-service
spec:
  selector:
    app: log-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP