apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: log-service
spec:
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: kafka-producer:latest