name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push App image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/log-service:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/log-service:${{ github.sha }}
          
    - name: Build and push Producer image
      uses: docker/build-push-action@v5
      with:
        context: ./producer
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/kafka-producer:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/kafka-producer:${{ github.sha }}
